name: "Configure Java and Gradle"
description: "Boilerplate steps"
runs:
  using: "composite"
  steps:

    # Checkout Code
    - name: Checkout
      uses: actions/checkout@v6

    # Setup JDK 21 to build properly
    - name: set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: temurin
        cache: gradle

    # Setup Gradle because without it, nothing happens
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
